services:
  - type: web
    name: face-attendance-backend
    env: docker
    dockerfilePath: Dockerfile
    dockerContext: .
    plan: free
    region: singapore
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: ALLOWED_ORIGINS
        value: "*"
